# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e5bd93af8c7929e64c1cf202518ad6ded526ca69f43342afcd3a6eb4ea543e9972d3971af343e1057b504e0f8c37b509c92d5af8b435aa368a0724520240f48

test:
  secret_key_base: 09e7804ce04cabcc398a7605c278f792855b9dfafd82ae0375ec35325552111cf5e37bd2e42067c69f5e82eaaa12f93f6734caaf62918e91c2b95b3d48fe70d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
